---
title: "괴델의 불완전성 정리"
author: "김진섭"
institute: "차라투(주)"
date: "2019-05-30"
output:
  xaringan::moon_reader:
    css: ["css/footer-header.css", "default"]
    lib_dir: libs
    nature:
      beforeInit: "js/macros.js"
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "4:3" 
subtitle: "제주대 경영정보학과 특강"
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(echo = FALSE, fig.align = "center")
library(knitr);library(DT);library(dplyr);library(data.table);library(rmarkdown);library(readr);library(purrr);library(tidyr)
```


layout: true

<div class="my-footer"><span><a href="https://www.zarathu.com">Zarathu Co.,Ltd</a>   
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
<a href="https://github.com/jinseob2kim">김진섭</a></span></div> 


---
# Executive Summary 

.large[
* 18/19 세기, 미적분학, 해석학의 발전과 함께 수학은 점점 기존의 직관과 상식에서 벗어나 추상화되었고, 많은 문제점들이 대두되었다.
]

--
.large[
* 특히 무한의 개념을 엄밀하게 다룰 필요성이 있었는데, **칸토어(Georg Cantor)**는 집합론의 논법으로 무한을 엄밀하게 정의하고 그것들의 크기를 비교하였다.
]

--
.large[
* 20세기 수학자들은 집합론을 이용, 수학의 기초를 구성하고 모순이 없는 수학체계를 만들 수 있다는 꿈으로 부풀어 있었으나, [러셀(Bertrand Russel)의 역설(paradox)](https://namu.wiki/w/%EB%9F%AC%EC%85%80%EC%9D%98%20%EC%97%AD%EC%84%A4)로 대표되는 "**자기언급의 역설**"은 집합론의 기초를 위태롭게 하였다.
]


---

.large[ 
* **힐베르트(David Hilbert)**는 "자기언급의 역설" 은 **수학의 명제**와 **메타수학(meta-mathematics)의 명제**를 구분하지 않아 일어나는 것으로 판단하였으며, 이를 잘 구분하는 공리계를 세심하게 설계할 수만 있다면 모순없는 수학체계를 만들 수 있다고 보았다.
]

--
.large[ 
* 그러나 **괴델(Kurt Gödel)**은 이 부분을 파고들어 메타수학의 명제를 수학의 명제로 바꾸는 **괴델수(Gödel number)** 라는 독창적인 아이디어를 제안, 메타수학의 명제를 수학 체계로 갖고 온 후 자기언급의 역설을 보여주었다. 즉, "**자기언급의 역설**" 을 피하기 위해 아무리 세심하게 공리계를 설계해도 그것을 피할 수는 없다는 것을 증명하였으며, 이것이 불완전성 정리이다.  
]

--
.large[
* 불완전성 정리로 인해 "**참이지만 증명불가능한 명제가 존재**" 하고 나아가 "**수학의 무모순성을 증명할 수 없음**" 이 증명되어 모순없는 완전한 수학체계의 꿈은 결국 산산조각이 난다.
]



---

class: center, middle

# 수학의 추상화


---

class: center, middle

# 집합론: 무한의 엄밀한 정의


---

class: center, middle

# 자기언급의 역설


---

class: center, middle

# 수학과 메타수학


---

class: center, middle

# 괴델수: 메타수학을 수학으로


---

class: center, middle

# 불완전성 정리 증명


---

class: center, middle

# 의의

---

class: center, middle

# END


